@@grammar :: TextGrammar

@@whitespace :: ?"[\t]+"

@@eol_comments :: ?"^(//.*|\s*)\n?"

start = grammar ;

tag = ?"[\w()/!<>\-\s,.]+" ;

given = ?"[^;|{}\n\[\]#]+" ;

statement = ?"[^|\[\]{}\n<>]+" ;

Literal = ?'[^;|"<>\[\]#{}]*' ;

literalAlternative::Literal = value:Literal ;

terminalSymbol::TerminalSymbol = ('"' literal:Literal '"' | ~literal:Literal);

nonterminalSymbol::NonterminalSymbol = "#" symbol:tag "#" ;

evalSymbol::EvalSymbol = statement:statement ;

conditionalSymbol::ConditionalSymbol = expression:(nonterminalSymbol | evalSymbol) [?"\s*\|\s*" given:given] ;

specialSymbol::SpecialSymbol = "{" statement:conditionalSymbol "}" ;

listSymbol::ListSymbol = "[" symbol:specialSymbol "]" ;

pythonSymbol::PythonSymbol = "<" statement:statement ">" ;

Symbol = listSymbol | specialSymbol | nonterminalSymbol | terminalSymbol;

adjectiveNoun::AdjectiveNoun = adjective:Literal "|" noun:Literal ;

entity = adjectiveNoun | literalAlternative ;

match::Match = lhs:entity "<->" rhs:entity ;

String::String = symbols:{Symbol}+ ;

alternatives = ";".{String}+ ;

productionRule::ProductionRule = symbol:tag ":" alternatives:alternatives ("\n" | $) ;

grammar::TextGrammar = rules:{productionRule}* $ ;

onlyString = @:String $ ;
