jobs:
  - ${{ each vmImage in parameters.vmImages }}:
    - ${{ each pythonVersion in parameters.pythonVersions }}:
        - job:
          displayName: ${{ format('OS:{0} PY:{1}', vmImage, pythonVersion) }}
          pool:
            vmImage: ${{ vmImage }}

          steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '${{ pythonVersion }}'

          - script: |
              sudo apt update && sudo apt install -y --no-install-recommends graphviz
            displayName: 'Install dependencies'

          - script: |
              pip install "textworld[full]>=.dev"
            condition: eq(variables.installFromSource, false)
            displayName: 'Install a prerelease of TextWorld from PyPi'

          - script: |
              setup.sh
              pip install -r requirements-full.txt
              pip install -e .
            condition: eq(variables.installFromSource, true)
            displayName: 'Install TextWorld from source'

          - script: |
              pip install pytest pytest-azurepipelines pytest-cov
              pytest --durations=10 --junitxml=junit/test-results.xml --cov=textworld --cov-report=xml --cov-report=html tests/ textworld/
            displayName: 'Run tests'

          - script: |
              curl -Os https://uploader.codecov.io/latest/linux/codecov
              chmod +x codecov
              for i in {1..5}; do ./codecov -t ${CODECOV_TOKEN} && break || sleep 30; done
            env:
              CODECOV_TOKEN: $(CODECOV_TOKEN)
            displayName: 'Publish coverage on Codecov'

          - task: PublishCodeCoverageResults@1
            inputs:
                codeCoverageTool: Cobertura
                summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
                reportDirectory: '$(System.DefaultWorkingDirectory)/**/htmlcov'